/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import tech.tablesaw.api.StringColumn;

public class Library {
    public StringColumn doSomething() {
        StringColumn nameColumn = StringColumn.create("Name", new String[]{"Alice", "Bob", "Carol"});
        return nameColumn;
    }

    public boolean someLibraryMethod() {
        return true;
    }
}
